import Vue from 'vue'
import Vuex from 'vuex'
import persistedState from 'vuex-persistedstate'
Vue.use(Vuex)

export default new Vuex.Store({
  plugins: [persistedState ()],
  state: {
    //从首页得到的食堂类型和食堂id
    canteenList:null,
    //从首页传的报餐的食堂
    mealCanteenList:null,
    //从首页传给订餐页配送和自提费用的权限
    power:null,
    //食堂地址
    canteenAddr:'',
    //选择配送地址
    chooseAddr:null,
    //备注
    remark:'',
    //购物车数组
    placeOrder:null,
    //购物车数据
    cartList:null,
    //外配配送费用
    giveCost:0,
    //自提配送费用
    oneCost:0,
    //购物车传递给确认订单需要的参数
    cartParams:null,
    //确认订单到支付页传递的参数
    paymentParams:null,
    //餐柜所需
    buffet:null,
    //结算价格
    resultPrice:null,
  },
  mutations: {
    //从首页得到的食堂类型和食堂id
    getCanteenList(state,playod){
      state.canteenList=playod
    },
    getMealList(state,playod){
      state.mealCanteenList=playod
    },
    getPower(state,playod){
      state.power=playod
    },
    //食堂地址
    getCanteenAddr(state,playod){
      state.canteenAddr=playod
    },
    //选择的配送地址
    getChooseAddr(state,playod){
      state.chooseAddr=playod
    },
    //备注
    getRemark(state,playod){
      state.remark=playod
    },
    //购物车数组
    getPlaceOrder(state,playod){
      state.placeOrder=playod
    },
    //购物车数据
    getCartList(state,playod){
      state.cartList=playod
    },
    //外卖配送费用
    getGiveCost(state,playod){
      state.giveCost=playod
    },
    //自提费用
    getOneCost(state,playod){
      state.oneCost=playod
    },
    getCartParams(state,playod){
      state.cartParams=playod
    },
    getPaymentParams(state,playod){
      state.paymentParams=playod
    },
    getBuffet(state,playod){
      state.buffet=playod
    },
    getResultPrice(state,playod){
      state.resultPrice=playod
    },
  },
  actions: {
    //从首页得到的食堂类型和食堂id
    setCanteenList({commit},playod){
      commit('getCanteenList',playod)
    },
    setMealList({commit},playod){
      commit('getMealList',playod)
    },
    setPower({commit},playod){
      commit('getPower',playod)
    },
    setCanteenAddr({commit},playod){
      commit('getCanteenAddr',playod)
    },
    setChooseAddr({commit},playod){
      commit('getChooseAddr',playod)
    },
    setRemark({commit},playod){
      commit('getRemark',playod)
    },
    setPlaceOrder({commit},playod){
      commit('getPlaceOrder',playod)
    },
    setCartList({commit},playod){
      commit('getCartList',playod)
    },
    setGiveCost({commit},playod){
      commit('getGiveCost',playod)
    },
    setOneCost({commit},playod){
      commit('getOneCost',playod)
    },
    setCartParams({commit},playod){
      commit('getCartParams',playod)
    },
    setPaymentParams({commit},playod){
      commit('getPaymentParams',playod)
    },
    setBuffet({commit},playod){
      commit('getBuffet',playod)
    },
    setBuffet({commit},playod){
      commit('getBuffet',playod)
    },
    setResultPrice({commit},playod){
      commit('getResultPrice',playod)
    },
  },
})
